### ISSUE TITLE
Need theory of operations/architecture documentation

### ISSUE THREAD

**Issue by mfischer-zd** [Nordstrom/chef-vault#109]
The documentation currently lacks coverage of architecture and theory of operations.  As a consequence it's difficult to scrutinize chef-vault to determine whether it's adequately secure and whether it's a good fit for one's environment.

Good job on the usage documentation, though!

**Comment by jf647** [comment]
I've created a THEORY.md document on the issue_109 branch if you'd like to take a look and see if it provides the level of detail you're looking for.

@moserke, if you can also take a gander and make sure that I haven't mis-spoken that would be great.

If this looks good, I'll make it part of v2.5.0, which I hope to ship tomorrow.
