### ISSUE TITLE
Can't decrypt stored pfx certificates

### ISSUE THREAD

**Issue by mrobinet** [Nordstrom/chef-vault#115]
I'm attempting use a .pfx SSL certificate that I've added to my vault but I get an error when the vault attempts to decrypt it:

```
PS C:\devtools\chef-repo> knife vault create certificates chefvault --file `'C:\devtools\chefvault.pfx`' --mode client --admins mrobinet --search `'role:empower-webserver OR role:empower-jenkins-slave`'
PS C:\devtools\chef-repo> knife vault show certificates chefvault --mode client
ERROR: Chef::EncryptedDataBagItem::DecryptionFailure: Error decrypting data bag value. Most likely the provided key is incorrect
```

I've tried this with a handful of other binary files and get the same result. Can chef-vault not store binary files?

**Comment by jf647** [comment]
While it might make it into a major refactor, for now I'm going to close this as "won't fix" for the reasons Kevin gave.
