### ISSUE TITLE
knife subcommands fail in cryptic fashion if you don't set --mode

### ISSUE THREAD

**Issue by jstange** [Nordstrom/chef-vault#117]
My first time dabbling with Vault. Loving it, but I burned an hour or two figuring out that I need to set --mode client (or set it in knife.rb) for it to successfully load existing data bag items. I reckon the error messaging could be adjusted to point one in the right direction.

    # knife vault create my_vault some_item '{ "data":"stuff" }' --mode client --search role:some-role
    # knife data bag show my_vault
    some_item
    some_item_keys

But then:

    # knife vault refresh my_vault some_item
    ERROR: ChefVault::Exceptions::ItemNotFound: my_vault/some_item does not exist, use 'knife vault create' to create.

Same error with *edit*, *delete*, or *rotate keys*; *show* fails with a similar complaint about the *_keys* item. Interestingly, *update* works.

The long and short is that *Chef::DataBagItem.load* is called in solo mode unless you say otherwise, and thus not trying to fetch my stuff via REST and not seeing it.

**Comment by jf647** [comment]
Closing for lack of feedback
