### ISSUE TITLE
Skip missing/invalid client rather than raising exception

### ISSUE THREAD

**Issue by normseth** [Nordstrom/chef-vault#127]
My organization uses both Vault and Chef Provisioning (nee Chef Metal).

Due (apparently) to hiccups with Provisioning, we have several times ended up a chef node that lacks a corresponding client.  

When chef-vault encounters this situation, it exits with an exception, leaving the vault unmodified.

It would be preferable if chef-vault simply skipped the missing client/node, rather than failing the entire operation. 

While the root issue is outside chef-vault, it seems like this situation will be increasingly common, as Provisioning enters broader use (and higher level orchestration, more generally).

**Comment by jf647** [comment]
I just pushed a branch that fixes this; can you try v2.4.1 and see if it does what you expect?  I emit a warning when the client is not found.

The 'skip if client not found' only applies when using a node as a client; I assume that if you try to use a node as an admin and it's not found that should still be a critical error.

**Comment by normseth** [comment]
Maybe I'm missing something simple here, but when I build and install the gem from the issue_127 branch, knife no longer recognizes the vault subcommand:

```
vagrant /chef-repo/tmp/chef-vault-issue_127 $ chef gem search --local chef-vault

*** LOCAL GEMS ***

chef-vault (2.4.0, 2.2.1)

vagrant /chef-repo/tmp/chef-vault-issue_127 $ knife vault show secrets_qa platform -M client 
couchbase:
  admin:
    password: Password1
<TRUNCATED>

vagrant /chef-repo/tmp/chef-vault-issue_127 $ gem build chef-vault.gemspec 
WARNING:  description and summary are identical
WARNING:  open-ended dependency on chef (>= 0.10.10, development) is not recommended
  if chef is semantically versioned, use:
    add_development_dependency 'chef', '~> 0.10', '>= 0.10.10'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: chef-vault
  Version: 2.4.1
  File: chef-vault-2.4.1.gem

vagrant /chef-repo/tmp/chef-vault-issue_127 $ sudo chef gem install ./chef-vault-2.4.1.gem 
Successfully installed chef-vault-2.4.1
Parsing documentation for chef-vault-2.4.1
Installing ri documentation for chef-vault-2.4.1
Done installing documentation for chef-vault after 0 seconds
1 gem installed
vagrant /chef-repo/tmp/chef-vault-issue_127 $ chef gem search --local chef-vault

*** LOCAL GEMS ***

chef-vault (2.4.1, 2.4.0, 2.2.1)
vagrant /chef-repo/tmp/chef-vault-issue_127 $ knife vault show secrets_qa platform -M client
FATAL: Cannot find sub command for: 'vault show secrets_qa platform -M client'
```

**Comment by jf647** [comment]
I can't repro that error on my system before or after installing the branched copy:

```
M00972939 ➜  chef-vault git:(issue_127) chef gem which chef-vault
/Users/x39d/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.4.0/lib/chef-vault.rb
M00972939 ➜  chef-vault git:(issue_127) knife vault show foo bar
foo: bar
id:  bar
M00972939 ➜  chef-vault git:(issue_127) gem build chef-vault.gemspec
WARNING:  description and summary are identical
WARNING:  open-ended dependency on chef (>= 0.10.10, development) is not recommended
  if chef is semantically versioned, use:
    add_development_dependency 'chef', '~> 0.10', '>= 0.10.10'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: chef-vault
  Version: 2.4.1
  File: chef-vault-2.4.1.gem
M00972939 ➜  chef-vault git:(issue_127) chef gem install chef-vault-2.4.1.gem
Successfully installed chef-vault-2.4.1
1 gem installed
M00972939 ➜  chef-vault git:(issue_127) chef gem which chef-vault
/Users/x39d/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.4.1/lib/chef-vault.rb
M00972939 ➜  chef-vault git:(issue_127) knife vault show foo bar
foo: bar
id:  bar
M00972939 ➜  chef-vault git:(issue_127)
```

**Comment by normseth** [comment]
k, i'm probably doing something silly.  will take a look later today.  tx.

**Comment by jf647** [comment]
I'm hoping to get 2.5.0 released with a bunch of fixes; given the amount of testing I've been doing I'm pretty confident this will come down to something silly like perms or directory mismatch (I notice you did `chef gem install` as root, which might have stuck it in `~root/.chefdk/gems` depending on whether you're doing `chef shell-init bash` globally or not).

If you do have a chance to confirm that the fix works for you Monday, it would be good to hear that it works outside of a test harness.

Thanks

**Comment by normseth** [comment]
Looks good.  Thanks for taking care of this so quickly!
