### ISSUE TITLE
Knife Vault Refresh Not Running on Server 2012R2

### ISSUE THREAD

**Issue by sfeeney22** [Nordstrom/chef-vault#129]
We've got some powershell workflows that are involved with our deployment code. They remote to a server and run some commands. One of the commands we need to run is the vault refresh (after a new node is added with the correct role) - it seems the "knife vault refresh Vault Credential -m client" hangs forever while processing. 

Running the same command on an 8.1 machine - is fine. 

So it seems something with the OS does not allow it to run. The chef/powershell versions are the same on both machines. We are running chef enterprise version 11.12.8, using vault 2.4.

**Comment by jf647** [comment]
Using the same channel to the 2012r2 server, do these commands work?

```
knife node list
knife vault show Vault Credential -M client
knife search node <SOLR query for your vault>
```

I tried this on a fresh 2012r2 VM and it seemed to work fine:

```
PS C:\Users\Administrator> $env:EDITOR = 'notepad'
PS C:\Users\Administrator> knife vault create foo bar
PS C:\Users\Administrator> knife vault update -S '*:*' foo bar
PS C:\Users\Administrator> knife vault refresh foo bar
PS C:\Users\Administrator> knife vault show foo bar
foo: bar
id:  bar
PS C:\Users\Administrator> knife search node '*:*'
1 items found

Node Name:   foo.nordstrom.net
Environment: foo-test
FQDN:
IP:
Run List:    recipe[foo]
Roles:
Recipes:
Platform:
Tags:
```

My gut feeling is that hanging forever sounds like an issue with network connectivity to the server.

I know we have had a Windows user report that `knife node search` for a complex query against an org with 3k nodes in it took a very long time (>3h).  Are you trying to refresh against an org of that size or with a particularly hairy SOLR query?

**Comment by sfeeney22** [comment]
I won't completely rule out network problems (as I've learned not to completely rule anything out) but its unlikley. We don't have issues between my desktop to the chef node and both the server and my desktop exist on the same switch. For what that's worth. 

The "knife search node '*:*' "  query actually exhibits the same behavior in not returning anything. Our organization has about 300 nodes, so I don't think we're hitting the same limits there. 

I'd be willing to consider the chef server as a bottleneck - except the fact that it works on my desktop at the same time - seems to indicate that is not the case. 

What hypervisor is your fresh VM on - maybe I'm hitting some issues there.

**Comment by jf647** [comment]
I was using an EC2 with their "standard" (i.e. Amazon prepared) 2012r2 image.   Set it up on a t2.medium instance type and those commands were over a VPN/VPC back to an on-prem Enterprise Chef 11.2.6 box.

When I say network connectivity, I'm was thinking more about window sizes and such.  Just as an example, PuTTY has a workaround for a problem with the Windows stack that causes git clones over SSH to hang after they have pulled everything but before they resolve deltas:

http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/winadj-success.html

The workaround fiddles with the TCP window size to stop this:

https://jira.atlassian.com/browse/STASH-3824

Obviously we're talking about different protocols, but that's what came to mind when you said that the same search hangs.

In terms of chef-vault, if the search hangs (and the chef API doesn't throw an exception), then vault operations that depend on search will hang as well.  We could put a timeout block around it, but I'm not sure what a safe default would be - there may be people with workflows whose long searches do successfully finish, so I'd be hesitant to possibly break those outside of a major version bump.

I assume you're hitting your Chef server over https?  It would be interesting to see a TCP trace to see if there are reasons the search is hanging.  Obviously unencrypted would be better, if you can hit the server on http.

**Comment by sfeeney22** [comment]
So after this message on Sunday I went to try your fixes and noticed the knife search from Thursday/Friday had finished. I kicked off another knife search - this time with the measure-command flag (to get times). Results are below:

PS C:\Users\XXXX> measure-command {knife search '*:*' -i}


Days              : 1
Hours             : 21
Minutes           : 44
Seconds           : 59
Milliseconds      : 785
Ticks             : 1646997850492
TotalDays         : 1.90624751214352
TotalHours        : 45.7499402914444
TotalMinutes      : 2744.99641748667
TotalSeconds      : 164699.7850492
TotalMilliseconds : 164699785.0492

So it seems eventually it works? I ran a wireshark while this was going on - there was no communication for quite some time until it came through. Any thoughts on this?

**Comment by jf647** [comment]
The internal person who reported the slow search didn't let it run to completion, so I had been working under the impression that it would hang forever.

On the trace, did you see a burst of results after performing the search and then nothing until the close?   Is there any payload in the final packets before the connection closes, or does it look like a socket-level close instead of an application-level close?

I'd open a issue with Chef (via the corp support if you're an enterprise customer, otherwise Github against the chef-server project) about the search issue, as that seems to be at the heart of it.

There is a possible change we can make which is to handle the results using a block.  Right now we do the entire search and then take the results and iterate over them like this:

    query.search(:node, search)[0].each do |node|

But even going back to Chef 10.34.6, you can pass a block to search and have it hand the rows off to you as they come in (sort of - it still seems to page 1000 at a time, but we could change that at the cost of more round-trips to the server).

Let me throw together a quick spike with that change and have you test it.

**Comment by sfeeney22** [comment]
Great thanks - I will open up an enterprise ticket as well. Will let you know what happens regardless.

**Comment by jf647** [comment]
I just pushed a branch spike_search_stream_results.  This handles the search results as a block:

    query.search(:node, search, 'X_CHEF_id_CHEF_X asc', 0, windowsize) do |node|

instead.  The window size defaults to 1000 as before but can be changed by setting the environment variable CHEF_SEARCH_WINDOW_SIZE to something else:

    > CHEF_SEARCH_WINDOW_SIZE=5 knife vault refresh foo bar
    chef-vault client search returned node foo
    chef-vault client search returned node bar

I also put in a debug puts statement to show the nodes as they come back, which might help to see if the results are bursty or not.

Can you see how that works with the default window size, and if the results hang try bringing it down to lower values to see if it makes a difference?

**Comment by sfeeney22** [comment]
Thanks - heading out to lunch but will try this afternoon.

**Comment by sfeeney22** [comment]
I pulled the code and compiled it (using rake) - manuall installed the gem on the server (gem install) - however knife vault is no longer recognized.

**Comment by jf647** [comment]
Someone else had this problem, and I think it came down to permissions.  Make sure (especially if you're using 'chef gem install') that you install and run as the same user.

There is nothing in the diff that would cause the entire plugin to stop being recognized, so I'm sure it will come down to something along these lines.

**Comment by sfeeney22** [comment]
I've confirmed I'm running as the right user both the vaul command that the 'gem install'. I'm out of the office today I'll take a look later this evening.

**Comment by jf647** [comment]
Perhaps roll back to the rubygems version and just manually make the changes shown in the diff to the working copy then?

There definitely seems to be something going wrong when people install gems they've built themselves, but I've never had it happen to me so I can't provide much guidance beyond guesses.  I'd prefer to not conflate that problem with the 'searches never complete' issue.

**Comment by jf647** [comment]
Any feedback on this?  Ultimately this is a 'knife search on Window' issue, but if the change provides improvement I'm willing to merge it for the next release.

**Comment by sfeeney22** [comment]
I haven't had a chance to move on this. Hopefully by the end of the week. We just did our renewal with Chef - so I'll be opening a support ticket with them per your advice. I'm fine if you want to close this as not a vault issue - and I will comment here with an update.

**Comment by jf647** [comment]
I'll mark this for closure when I'm doing the prep for 2.6.0; hopefully you can try the patch by then and provide feedback as to whether we should add the search changes to that release.

**Comment by sfeeney22** [comment]
So finally have some resolution here. For whatever reason chef-client 18.6 now works. Its possible it was some combination of windows updates and chef client or what. But everything now works.

**Comment by jf647** [comment]
Thanks for letting us know
