### ISSUE TITLE
clean_unknown_clients not working

### ISSUE THREAD

**Issue by plu** [Nordstrom/chef-vault#133]
Hi,

I've tried to use the `--clean-unknown-clients` on `2.4.0`, but it does not seem to be working.

I can see this warning: `WARNING: No clients were returned from search, you may not have got what you expected!!`

So I started digging. Here it should catch the `ChefVault::Exceptions::ClientNotFound` exception: https://github.com/Nordstrom/chef-vault/blob/5b06f5ba03385f362a6635a10e04b7f6ed595a28/lib/chef-vault/item.rb#L116

But it never does reach this `rescue` block. So checking further for `ClientNotFound`, turns out it's never raised in the code base at all. Maybe I'm overlooking something, but I think this is the root cause for the issue. I'm not sure where exactly to raise the exception without breaking other things. So I'd rather not provide a half-working pull request, instead I'm kindly asking you to have a look at this issue once you find some spare time :).

Thanks,
plu

**Comment by jf647** [comment]
That exception is raised, here:

https://github.com/Nordstrom/chef-vault/blob/master/lib/chef-vault/item.rb#L282

`ChefVault::Item#clients` calls `ChefVault::Item#load_client` which can raise `ChefVault::Exceptions::ClientNotFound`.

The warning message is unrelated to the operation of `--clean-unknown-clients`.  This means that what you passed to -S didn't return anything.  To check your query, pass it to `knife search node ...` first.  If that returns nothing, the vault create/update/whatever will fail.  You'd get the same warning even without `--clean-unknown-clients`

Can you provide all the commands you're using, from vault creation on so I can try to reproduce (or create a PR with an cucumber feature that exposes it)?

**Comment by plu** [comment]
Oh. Lesson learned: Never trust the Github code search: https://github.com/Nordstrom/chef-vault/search?utf8=%E2%9C%93&q=ClientNotFound

I'll dig some more and let you know the findings!

**Comment by plu** [comment]
Yesterday I was just cleaning up the old clients by hand via `knife data bag edit foo bar_keys`.

Right know I can reproduce it by manually doing this:

```
knife vault create roles test '{}' -S 'role:haproxy' -A plu
knife data bag show roles test_keys -F json
```

```json
{
  "id": "test_keys",
  "admins": [
    "plu"
  ],
  "clients": [
    "haproxy"
  ],
  "search_query": "role:haproxy",
  "haproxy": "key1",
  "plu": "key2"
}
```

Yestterday, there was one old node listed in the `clients` array, that did not exist anymore. Also its key was listed in the data bag. Now that I had cleaned up the old node already, I will add one back manually to reproduce the behaviour:

```
knife data bag edit roles test_keys
# vi...
knife data bag show roles test_keys -F json
```

```json
{
  "id": "test_keys",
  "admins": [
    "plu"
  ],
  "clients": [
    "haproxy",
    "doesntexist"
  ],
  "search_query": "role:haproxy",
  "doesntexist": "key3",
  "haproxy": "key1",
  "plu": "key2"
}
```

Now I'd expect that this command would remove the non existing client:

```
knife vault rotate keys --clean-unknown-clients roles test
WARNING: No clients were returned from search, you may not have got what you expected!!
```

But it didn't:

```
knife data bag show roles test_keys -F json
```

```json
{
  "id": "test_keys",
  "admins": [
    "plu"
  ],
  "clients": [
    "haproxy",
    "doesntexist"
  ],
  "search_query": "role:haproxy",
  "doesntexist": "key3",
  "haproxy": "key1",
  "plu": "key2"
}
```

I think I got a bit closer to the problem by adding some output to `ChefVault::Item#load_client`:

```ruby
277   def load_client(client)
278     $stderr.puts "trying to load client: #{client}"
```

And some more here:

```ruby
 37   def clients(search=nil, action=:add)
 38     if search
 39       results_returned = false
 40
 41       query = Chef::Search::Query.new
 42       $stderr.puts "searching for #{search}"
```

Output:

```
knife vault rotate keys --clean-unknown-clients roles test
searching for name:haproxy
trying to load client: haproxy
searching for name:doesntexist
WARNING: No clients were returned from search, you may not have got what you expected!!
```

So when the search does not return anything, it does not even try to `ChefVault::Item#load_client`, hence no exception will be raised and the cleanup cannot happen either.

**Comment by plu** [comment]
https://github.com/Nordstrom/chef-vault/blob/master/features/clean_unknown_clients.feature#L23

This will already remove the client + its key from the vault data bag, right?

So this will be kind of a noop:

https://github.com/Nordstrom/chef-vault/blob/master/features/clean_unknown_clients.feature#L24

But this will still be happy because of `delete client 'one'` did its job properly before:

https://github.com/Nordstrom/chef-vault/blob/master/features/clean_unknown_clients.feature#L25

**Comment by plu** [comment]
By the way: The last time I was using Chef was many months ago, before chef-vault existed. Now being back in the Chef business with chef-vault it's such a joy to handle your secrets in a clean & safe way! I wanted to thank you for this great helper in my daily life :)!

**Comment by jf647** [comment]
Ah. that makes sense.  The original contributed implementation wed the cleanup to a successful search.

The desired behaviour (decoupling the cleanup and search results) should be easy to assert using a feature test, and I'll try to get this into the upcoming v2.5.0 release.

**Comment by plu** [comment]
Thanks :)!

**Comment by jf647** [comment]
Okay, I've coded up tests to expose this and done some refactoring of how --clean-unknown-clients is implemented which I think fixes it.  If you can try the version on branch issue_133, and take a look at the new scenario added to `features/clean_unknown_clients.feature` to see if it matches your use case.

There was a bit more work involved here than I expected, because the original code made it impossible to ever remove a client if the node object had been deleted.  However, since the clean unknown code has extensive feature tests, I feel pretty confident.  I might throw a few more tests around the uncovered subcommands that call into the same parts of the code just to be safe.

I also ended up enhancing the step definitions so that you can now assert on whether a given entry exists in the _keys data bag, or in the clients or admins array.  The old definitions just did regex matching on the output of `knife vault show`; the new definitions parse the output of `knife data bag show` as JSON and then assert things about the underlying data structure, which should be useful for contributors who want to write new feature tests.

**Comment by plu** [comment]
That was quick, thank you for fixing this issue so fast!

I can confirm that it's working just perfect for my use case:

```
plu@plumini ~/Development/chef-vault[issue_133]$ chef gem install ./pkg/chef-vault-2.5.0.gem
WARNING:  You don't have /Users/plu/.chefdk/gem/ruby/2.1.0/bin in your PATH,
          gem executables will not run.
Successfully installed chef-vault-2.5.0
1 gem installed
plu@plumini ~/Development/chef-vault[issue_133]$ cd ../cookbooks
direnv: loading .envrc
direnv: export +CHEF_CLIENT_KEY +CHEF_COOKBOOK_PATH +CHEF_DATA_BAG_PATH +CHEF_DNS_CONTEXT +CHEF_DNS_PASSWORD +CHEF_DNS_USERNAME +CHEF_SERVER_URL +CHEF_USER_NAME +CHEF_VALIDATION_CLIENT_NAME +CHEF_VALIDATION_KEY +CHEF_VAULT_MODE +VAGRANT_DEFAULT_PROVIDER ~PATH
plu@plumini ~/Development/cookbooks[master]$ knife vault rotate keys --clean-unknown-clients roles test
Removing unknown client 'doesntexist'
plu@plumini ~/Development/cookbooks[master]$ knife vault rotate keys --clean-unknown-clients roles test
plu@plumini ~/Development/cookbooks[master]$
```

:+1:
