### ISSUE TITLE
Refresh did not re-encrypt for an admin's new key

### ISSUE THREAD

**Issue by dblessing** [Nordstrom/chef-vault#145]
One of our admins had to regenerate his key. We ran a `knife vault refresh <bag> <item>` several times but the admin could not decrypt the item. Finally we removed him as an admin on the item and re-added and he was able to access. Shouldn't `knife vault refresh` detect the changed key and re-encrypt for the admin?

**Comment by jf647** [comment]
`knife vault refresh` only re-applies the clients SOLR query and adds new clients.

To add a new administrator or update the admins with new public keys, you want `knife vault update`.

This is called out explicitly in THEORY.MD but not in KNIFE_EXAMPLES.md, so I'll try to clear that up for 2.6.0.

**Comment by dblessing** [comment]
@jf647 what args would I pass to `knife vault update` to refresh an existing admin? I ran `knife vault update` at one point with other args and it did not update the admin in question. It was only after I manually removed the admin and re-added via `knife vault update <vault> <item> -A <admin>` that it finally worked.

Thanks for the clarification.

**Comment by jf647** [comment]
The way it should work is that the list of admins to operate on is the the user running knife, plus any admins that you pass using -A or via the config setting in knife.rb.

For each of the admins, it pulls the public key and encrypts the shared secret for them.  So `knife vault update vault item -A admin_who_regenerated` (or if that admin was in your knife.rb list of admins) should have re-generated the key for them.

Do you have a set of steps to reproduce the error?

**Comment by jf647** [comment]
Any feedback on the steps to repro this error?  If not, I'll be closing this when we wrap up work on the upcoming 2.6.0 release.

Thanks

**Comment by jf647** [comment]
Closing for lack of feedback
