### ISSUE TITLE
Testing a cookbook that uses chef-vault in test-kitchen and chef-zero

### ISSUE THREAD

**Issue by iroller** [Nordstrom/chef-vault#146]
Trying to create some tests in test-kitchen for a cookbook that uses chef-vault. The cookbook actually executes `ChefVault::Item.load(...)`. So I need to create that vault item in my test recipe.

I found [chef_vault_item](https://github.com/opscode-cookbooks/chef-vault/blob/master/libraries/chef_vault_item.rb) lwrp and trying to use it to create new vault:

```
chef_vault_secret 'testitem' do
  data_bag 'testbag'
  admins 'hello-world-ubuntu-1204'
  raw_data({ key: 'data' })
  search '*:*'
  action :nothing
end.run_action(:create)

include_recipe "my-cookbook-to-test"
```

However it fails with 
```
ChefVault::Exceptions::AdminNotFound
------------------------------------
FATAL: Could not find hello-world-ubuntu-1204 in users or clients!
```

And there're actually no clients or users in chef-zero:
```
root@5a51fe47d4ca:~# knife client list -c /tmp/kitchen/client.rb -z

root@5a51fe47d4ca:~# knife user list -c /tmp/kitchen/client.rb -z

root@5a51fe47d4ca:~# knife node list -c /tmp/kitchen/client.rb -z
hello-world-ubuntu-1204
```

Any ideas on how to work it around?

**Comment by iroller** [comment]
^ping @jtimberman

**Comment by jf647** [comment]
This should be directed at the [chef-vault cookbook](https://github.com/opscode-cookbooks/chef-vault) (managed by Chef as opposed to Nordstrom, as the LWRP is their code.
