### ISSUE TITLE
knife boostrap not picking up nodes from search query of vaults

### ISSUE THREAD

**Issue by saimak** [Nordstrom/chef-vault#148]
knife bootstrap <IP> --ssh-user <user name> --config <path to config> --environment <env name> --node-name xyz-123 --bootstrap-vault-json {"vault":"item"} --sudo --run-list recipe[testing_1]

Gives WARNING: No clients were returned from search, you may not have got what you expected!!
Although, vault has search query (name:xyz*) associated to it and results in nodes which have name starting from xyz.

Why knife bootstrap is not getting node names and resulting in WARNING ?

**Comment by jf647** [comment]
Issues with knife-bootstrap should be opened against the [chef](https://github.com/chef/chef) repository.
