### ISSUE TITLE
Need validation for item id: property

### ISSUE THREAD

**Issue by kbaltrinic** [Nordstrom/chef-vault#149]
I had a devil of a time trying to figure out what was going on with a new item that I was adding to our ssl-certificates vault.  When I ran the `knife vault create ssl-certificates item-name -J item.json -A... -S...` command, it reported success.  But when looking on the chef server, I would only see an `item-name.net_keys` item without any matching `item-name` item in the data bag.  Moreover all subsequent attempts to interact with that item via `knife vault` would fail with a message: `ERROR: ChefVault::Exceptions::ItemNotFound: ssl-certificates/item-name does not exist, use 'knife vault create' to create.`

In the end, it turned out to be a cut and past error inside my .json file.  I had failed to update the `id` property and so the id property was the same as another already existing item in that data bag.  As a result, instead of writing a new `item-name` item into the bag, it was overwriting the `old-item-name` item!  Suffice it to say **this is bad**.

Knife vault needs to validate that the id value of the json matches the name of the item being created/updated and if it does not match, fail with an appropriate message.

Strictly speaking this issue may properly belong to the knife utility itself.  I did not test it with a regular data bag but they may present the same problem.  However, it is especially problematic for vault and I think vault should protect itself defensively from this issue.

This is with chef-vault 2.5.0.

**Comment by jf647** [comment]
`knife data bag create` does let you specify an item name on the command line, then change that item name by changing the 'id' attribute.  The issue with `knife vault create` is that the name of the keys item has been set prior to letting the user edit the data bag (or in your use case populate it from the JSON document).

It should be fairly simple to add validation to ensure that the id of the keys data bag item equals the name of the data bag item suffixed with _keys, and bomb out if that isn't the case.  With luck, just a couple of lines added below `validate_id!(item_id)` in `ChefVault::Item#save`.

As this is more an enhancement to protect users from invalid input as opposed to a bug in chef-vault itself, I'll target this for the next release, which I hope should be out in the next month or so.

**Comment by kbaltrinic** [comment]
Works for me.  Anyone who shoots them self in the foot like I did in the mean time will hopefully find this post.

**Comment by jf647** [comment]
I've added protection for this in the branch issue_149_validate_id, which I plan to merge into the upcoming 2.6.0 release by end of week.
