### ISSUE TITLE
Why new node created after the secret been made, never be able to decrypt the vault item

### ISSUE THREAD

**Issue by chrisduong** [Nordstrom/chef-vault#153]
Hi,

I created a secret with `--search option` is roles:common.
I bootstrapped the node with `common` role.
Then  add the recipe -called update DNS which later will require a AWS API secret ( that I had created before with chef vault). 
However, the new node still cannot decrypt the secret.
The old node still be able to decrypt the secret.

Please help what should I do to fix this. I'm still not so sure how chef vault does. Thanks a lot.

**Comment by jf647** [comment]
Did you refresh the vault after bootstrapping the new node?

The search query is only processed during update (in which case it must be passed via -S on the command line) or during refresh.  It doesn't automatically update whenever a new node is added to the Chef server.

You may want to read through THEORY.md in the distribution to understand what's going on behind the scenes.

**Comment by chrisduong** [comment]
Hi @jf647 ,

The command `knife vault refresh` did update the new node.
Thank you very much :)
