### ISSUE TITLE
knife vault create examples using node/client names?

### ISSUE THREAD

**Issue by phene** [Nordstrom/chef-vault#157]
I'm experimenting with chef-vault right now and do not want to use roles to limit how secrets are shared to various nodes/clients. How can I use the `--search` option to limit only by nodes with specific names/fqdns?

The docs say it's a solr query, but when I try to specify: `--search "app1.local OR app2.local"` I get a `ERROR: JSON::ParserError: OR is not valid JSON!`

I found that I can specify those clients with the `--admins` option, but I also get a warning: 
```
WARNING: app1.local not found in users, trying clients.
WARNING: app2.local not found in users, trying clients.
```

**Comment by jf647** [comment]
Play around with `knife search node` to find the query that works for you.  For hostnames, use `name:hostname`:

```
> knife search node 'name:i-2f1a78d9'
1 items found

Node Name:   i-2f1a78d9
```

The Chef docs on how you can search are here: http://docs.chef.io/chef_search.html

I will say that we find using environments to be better than locking down to specific hostnames, though this depends on whether you're using per-app (and thus small) environments or big ones that map to deployment phases (dev/test/prod/etc.)

**Comment by phene** [comment]
Ok, the problem is probably somewhere in chef. Based on the docs, this should work:
```
$ knife search node 'name:app1.local OR name:app2.local'
ERROR: ArgumentError: Type must be a string or a symbol!
```

**Comment by jf647** [comment]
That is strange, because the general form does work for me:

```
> knife search node 'name:i-2f1a78d9 OR name:i-75fd6283'
2 items found
...
```

I'd run that knife command with -VV to see if that sheds any light on the problem and if necessary open an issue against chef/chef

**Comment by phene** [comment]
Looks like a bug in Chef 11 (which I'm stuck on for the time being). Thanks for your feedback!
