### ISSUE TITLE
ChefVault::Item.refresh

### ISSUE THREAD

**Issue by dgoradia-atlas** [Nordstrom/chef-vault#168]
Saw on your changelog: 
```
ChefVault::Item now has a #refresh method which can be used to programatically perform the same operation as knife vault refresh
```

But I'm getting `undefined method 'refresh' for ChefVault::Item:Class`.

**Comment by jf647** [comment]
It's an instance method, so you have to call `::load`, then call `#refresh` on that.

This is how it's being used in the knife subcommand:

https://github.com/Nordstrom/chef-vault/blob/v2.6.0/lib/chef/knife/vault_refresh.rb#L38-39

**Comment by jf647** [comment]
I'm assuming this can be closed?

**Comment by dgoradia-atlas** [comment]
Yes, thank you.
