### ISSUE TITLE
Knife vault stopped working after chefdk & chef-client upgrade

### ISSUE THREAD

**Issue by threezerous** [Nordstrom/chef-vault#180]
I upgraded by chef-client to 12.4.1 and chefdk 0.7.0 on a windows host. Also installed gem chef-vault after ensuring that the PATH is set to C:\Users\ssonker\.chefdk\gem\ruby\2.1.0\bin.

However knife vault plugin still seems to be missing.
```
SSonker@NYCSSONKER ~
$ knife | grep vault

SSonker@NYCSSONKER ~
$

$ knife vault update racknstack_new TEST -S "run_list:recipe\[webmd-rackandstack\:\:racknstack\]"
FATAL: Cannot find sub command for: 'vault update racknstack_new TEST -S run_list:recipe\[webmd-rackandstack\:\:racknstack\]'
Available subcommands: (for details, knife SUB-COMMAND --help)
```

Appears I am missing something obvious, since others have it working for most part as seen here. But can't seem to nail it. Any suggestions are truly appreciated.

Thanks

**Comment by jf647** [comment]
What about `chef gem list | grep chef-vault`?

chef-vault 2.5.0 comes with ChefDK, so this feels like you're getting a restricted load path somehow.  You don't have one of those magic shell helpers that runs things under 'bundle exec' if you have a Gemfile in the directory, do you?  That can prevent knife from seeing any plugins that aren't also in the bundle.

**Comment by threezerous** [comment]
```
SSonker@NYCSSONKER ~
$ gem list | grep chef-vault
chef-vault (2.6.1)
```

I am using Git bash to run above commands and I do run bundle exec to run of my serverspec scripts. But I am not sure if the above commands are being run under bundle exec. I don't think so, but if there is a way to check let me know

**Comment by threezerous** [comment]
The issue was resolved after I updated the path to use C:\opscode\chefdk\embedded\bin.
Thanks for looking into it
