### ISSUE TITLE
Can't create anything. 

### ISSUE THREAD

**Issue by georeith** [Nordstrom/chef-vault#183]
Specs:
 - chef: 12.4.2
 - chef-zero

Attempting to run any `knife vault create` command raises a `TypeError: no implicit conversion of nil into String`.

Here is a verbose run with stack trace: 

**COMMAND:**  
`knife vault create certificates test '{"key":"value"}' -VV`

**OUTPUT:**
```
INFO: Using configuration from /Users/georgereith/documents/repos/spawn/chef/.chef/knife.rb
INFO: Started chef-zero at chefzero://localhost:8889 with repository at .
  One version per cookbook
  clients at /Users/georgereith/Documents/repos/spawn/chef/clients
  cookbooks at /Users/georgereith/Documents/repos/spawn/chef/cookbooks, /Users/georgereith/Documents/repos/spawn/chef/site-cookbooks
  data_bags at /Users/georgereith/Documents/repos/spawn/chef/data_bags
  environments at /Users/georgereith/Documents/repos/spawn/chef/environments
  nodes at /Users/georgereith/Documents/repos/spawn/chef/nodes
  roles at /Users/georgereith/Documents/repos/spawn/chef/roles
  users at /Users/georgereith/Documents/repos/spawn/chef/users
  policies at /Users/georgereith/Documents/repos/spawn/chef/policies

DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: #<ChefZero::RestRequest:0x007f83da21aad8 @env={"SCRIPT_NAME"=>"", "SERVER_NAME"=>"localhost", "REQUEST_METHOD"=>"GET", "PATH_INFO"=>"/users/", "QUERY_STRING"=>nil, "SERVER_PORT"=>8889, "HTTP_HOST"=>"localhost:8889", "rack.url_scheme"=>"chefzero", "rack.input"=>#<StringIO:0x007f83da21ad08>}, @rest_base_prefix=["organizations", "chef"]>
DEBUG:
DEBUG: No chefignore file found at /Users/georgereith/Documents/repos/spawn/chef/chefignore no files will be ignored
DEBUG: No chefignore file found at /Users/georgereith/Documents/repos/spawn/chef/chefignore no files will be ignored
DEBUG:
--- RESPONSE (200) ---
{
  "deploy": "chefzero://localhost:8889/users/deploy",
  "george": "chefzero://localhost:8889/users/george"
}

--- END RESPONSE ---
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
/Library/Ruby/Gems/2.0.0/gems/chef-vault-2.6.1/lib/chef-vault/item_keys.rb:33:in `initialize': no implicit conversion of nil into String (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/chef-vault-2.6.1/lib/chef-vault/item_keys.rb:33:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/chef-vault-2.6.1/lib/chef-vault/item_keys.rb:33:in `add'
	from /Library/Ruby/Gems/2.0.0/gems/chef-vault-2.6.1/lib/chef-vault/item.rb:121:in `block in admins'
	from /Library/Ruby/Gems/2.0.0/gems/chef-vault-2.6.1/lib/chef-vault/item.rb:117:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-vault-2.6.1/lib/chef-vault/item.rb:117:in `admins'
	from /Library/Ruby/Gems/2.0.0/gems/chef-vault-2.6.1/lib/chef/knife/vault_create.rb:84:in `rescue in run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-vault-2.6.1/lib/chef/knife/vault_create.rb:57:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.4.2/lib/chef/knife.rb:425:in `block in run_with_pretty_exceptions'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.4.2/lib/chef/local_mode.rb:39:in `with_server_connectivity'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.4.2/lib/chef/knife.rb:424:in `run_with_pretty_exceptions'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.4.2/lib/chef/knife.rb:215:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.4.2/lib/chef/application/knife.rb:142:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.4.2/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:23:in `load'
	from /opt/chefdk/bin/knife:23:in `<main>'
```

**Comment by dougireton** [comment]
Can you post your knife.rb? Here's another issue where the knife.rb caused a similar issue:
https://github.com/Nordstrom/chef-vault/issues/94

**Comment by georeith** [comment]
@dougireton 

Here's my knife.rb, you think it's due to cookbook_path being an array?

```ruby
cookbook_path    ["cookbooks", "site-cookbooks"]
node_path        "nodes"
role_path        "roles"
environment_path "environments"
data_bag_path    "data_bags"
encrypted_data_bag_secret "data_bag_key"
chef_zero.enabled = true

knife[:editor] = "vim"
knife[:berkshelf_path] = "cookbooks"

knife[:vault_mode] = 'solo'
knife[:vault_admins] = ['george', 'deploy']

Chef::Config[:ssl_verify_mode] = :verify_peer if defined? ::Chef

# You can ovveride and add custom settings by adding a knife.local.rb file
if ::File.exist?(File.expand_path("../knife.local.rb", __FILE__))
  Chef::Config.from_file(File.expand_path("../knife.local.rb", __FILE__))
end
```

**Comment by georeith** [comment]
@dougireton I tried changing `cookbook_path` to a string and it still occures

**Comment by jf647** [comment]
I'm not sure if these two config lines are compatible:

```
chef_zero.enabled = true
knife[:vault_mode] = 'solo'
```

Solo will make chef-vault try to modify files assuming you're in the repo directory.  Can you try adding `-M client` to the chef-vault command line, or can you confirm that you're in the repo dir when you run this?

Ideally, chef-vault would not have it's own idea of whether it's modifying files on disk or using the API: it would just use the -z switch (which is what `chef_zero.enabled=true` effectively does) to make this decision.  The code predates the existence of chef-zero though, and so there's still this weird hybrid mode, and one which defaults to file-based access instead.

If the `-M client` works, then you should change your knife.rb to have `knife[:vault_mode] = 'client'` instead.

If it doesn't, then can you add a list of what the directory structure looks like underneath where you are?  Line 33 of item_keys.rb is where it tries to check if the keys data bag has an entry for `admins` or `clients`, which suggets that maybe you are trying to do this operation on a file-based repo that doesn't have a `VAULTNAME/ITEMNAME_keys.json` file in it.

**Comment by georeith** [comment]
@jf647 Thanks for that information I was not sure what to run it as there and had tried both, I was in repo directory. I think it should work fine in client mode as I can see it successfully spins up chef-zero and is using the correct address for requests.

I've realised the cause of this is that I was setting the node_name in the vagrant provision and not on the actual node. So it was pulling nil in where it sets the list of admins. I've set it on the node and it now works.

I'm now getting different error when attempting to create a vault:
`No keys defined for test (ChefVault::Exceptions::NoKeysDefined)`

But this particular issue is solved. Thanks guys.

**Comment by jf647** [comment]
That means that chef-vault was unable to find any of your admins or clients.  Basically, when the bag was saved, there were no public keys with which to encrypt the shared secret.  Because the shared secret only exists as a 1..n set of encrypted copies (each for a different public key), this means that the shared secret would pass out of existence, leaving you with no way to decrypt the data in the encrypted data bag.

In such a case, chef-vault will die rather than leave you with irretrievable data.

Based on your knife.rb, it should be picking up the keys for the admins george and deploy, but do those exist under your clients directory?  When using chef-zero, all traffic hits it, so the public keys of the admins have to be there as `clients/$ADMINNAME.json`.

Again, this hybrid setup tends to cause problems.  If you're hitting the chef server directly, both the queries for admins and the saving of the data bag hit the real server.  If you're using chef-zero, those both hit chef-zero, which might not be populated with admin clients.  If you're using solo mode, the queries for admins and nodes hit the server, but the data bag saving hits local disk.
