### ISSUE TITLE
OpenSSL error if private key does not match used public key

### ISSUE THREAD

**Issue by moserke** [Nordstrom/chef-vault#43]
"OpenSSL::PKey::RSAError: padding check failed" error received if the private key used to try and decrypt the value is not the pair of the public key used to encrypt the value.  This can be received if the client/admin pem is regenerated after doing the encryption with chef-vault and the vault is not updated.

This is a VALID error, but need to add a better exception message!

**Comment by jf647** [comment]
Better [late](https://github.com/Nordstrom/chef-vault/blob/issue_43/lib/chef-vault/item.rb#L99-105) than never, I suppose:

```bash
> knife vault show test item -z -c knife.rb -u one -k one.pem
ERROR: ChefVault::Exceptions::SecretDecryption: test/item is encrypted for you, but your private key failed to decrypt the contents.  (if you regenerated your client key, have an administrator of the vault run 'knife vault refresh')
```

This will make it into the next release, which will be v2.4.1 or v2.5.0 depending on whether any of the issues I can get through add functionality or just fix bugs.
