### ISSUE TITLE
Does chef-vault require that a chef solo node be on a chef server?

### ISSUE THREAD

**Issue by dawilliams** [Nordstrom/chef-vault#58]
Hello,

I'm trying to try out chef-vault on a vagrant windows 2012 client using the chef solo provisioner.  I'm running chef-vault in solo mode but I don't see a way to list the chef solo node since the search option looks on the chef server.  Am I missing something or do I have to use a chef server?

Thanks,

David

**Comment by AnneTheAgile** [comment]
ty @daxgames , I will try your method. I'm  new and I found this from Google. It does seem like chef-zero is the right way to go as chef-solo will be deprecated at some point per; https://www.chef.io/blog/2014/06/24/from-solo-to-zero-migrating-to-chef-client-local-mode/

**Comment by splisson-altair** [comment]
@daxgames thanks for your solution, now I get OpenSSL::PKey::RSAError       
-----------------------       
padding check failed 
Got to figure the issue

**Comment by jf647** [comment]
I've actually got a pattern for using chef-vault with Test Kitchen, and next week I hope to have a gem and a cookbook released that makes it super easy to do this.  For now, you might want to look at my dissertation in this TK issue:

https://github.com/test-kitchen/test-kitchen/issues/602

What I do today is create a fixture cookbook that programmatically creates a vault item, encrypted for all nodes (which in TK is just the node under test).  That goes before my cookbook under test in the runlist (via .kitchen.yml), so the fixture cookbook creates the secret and the real cookbook uses the secret.

The TK issue linked above creates a problem where if the converge step fails, you can't converge a second time.  The solution is to nuke the TK chef-repo using `kitchen exec -c 'sudo rm -rf /tmp/kitchen'`, which will result in the node re-registering and creating a new keypair and vault on the next converge.

Look for more info about the gem and cookbook soon.

**Comment by jf647** [comment]
As to this thread itself, are there any specific issues with solo mode that are not working with v2.4.0?  This issue has been open way too long and if there are failing scenarios, I'd like to at least get the Aruba suite extended to cover them, even if we can't fix them immediately.

**Comment by jf647** [comment]
Closing for lack of further feedback.
